# Generated by Django 4.0.4 on 2022-05-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('poster', models.ImageField(upload_to='movies', verbose_name='Poster')),
                ('poster_url', models.URLField()),
                ('description', models.TextField(verbose_name='Plot')),
                ('released', models.DateField(verbose_name='Released Date')),
                ('director', models.CharField(max_length=50, verbose_name='Directors')),
                ('actors', models.CharField(max_length=100, verbose_name='Actors')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('dislikes', models.IntegerField(verbose_name='Dislikes')),
            ],
            options={
                'verbose_name': 'Movie',
            },
        ),
    ]
